### ISSUE TITLE
No Dockerfile for collectorforkubernetes container

### ISSUE THREAD

**Issue by max-rocket-internet** [outcoldsolutions/collector#1]
The one used here:
https://github.com/outcoldsolutions/collector/blob/master/kubernetes/collectorforkubernetes.yaml#L218

Would be good to know what is used here and how it's built.

**Comment by outcoldman** [comment]
@max-rocket-internet our collector is a software, which requires the license, we distribute it only in the binary form.
There is no much value in the Dockerfile, as this is a simple alpine Linux with our collector and configuration file.

**Comment by max-rocket-internet** [comment]
OK. I assumed it was open source since it was on Github.
